### ISSUE TITLE
Warning: Module 'cross-fetch/polyfill' Not ESM in Angular Build

### ISSUE THREAD

**Issue by Shamshiel** [meilisearch/meilisearch-js-plugins#1269]
**Description:**
During the Angular build process, a warning is issued regarding the module `cross-fetch/polyfill` being used by `node_modules/meilisearch/dist/bundles/meilisearch.esm.js`. 

**Expected Behavior:**
The expectation is that `meilisearch.esm.js` is compliant with ESM standards.

**Current Behavior:**
Currently, the module `cross-fetch/polyfill` appears to be either a CommonJS or AMD module, which could potentially cause optimization bailouts and hinder the build performance. The specific warning is as follows:

`
▲ [WARNING] Module 'cross-fetch/polyfill' used by 'node_modules/meilisearch/dist/bundles/meilisearch.esm.js' is not ESM. CommonJS or AMD dependencies can cause optimization bailouts.
`

Environment:
- instant-meilisearch version: v1.0.0

**Comment by flevi29** [comment]
This is a `cross-fetch` issue. Doesn't directly support ESM, in fact even uses an older `node-fetch` because latest is ESM only, at some point might even stop getting security updates (if it didn't already). Not sure how much this impacts tree shaking on browser builds or if it matters at all.

Tangent: As long as we want to support decade old end of life browsers, and fringe use cases, problems like these are unavoidable. If we'd only develop libraries for bundlers and not directly for every use case in existence.

**Comment by flevi29** [comment]
If we'd drop support for EOL Node.js versions, we could drop `cross-fetch`. Even though it's marked as experimental, `undici` `fetch` is built into Node.js 18 (Maintenece version, not even LTS at this point https://github.com/nodejs/Release), it's officially supported, and it has matured enough I'd say.

**Comment by flevi29** [comment]
There are [a few issues related to ESM on `cross-fetch`](https://github.com/lquixada/cross-fetch/issues?q=is%3Aissue+is%3Aopen+label%3Aesm). These are not getting fixed, I don't think so. Package is not very active, questionably maintained. We have three options:

- keep using `cross-fetch` despite this
- switch to `axios` or something similar (that would mean no support for deno theoretically as it doesn't implement XHR, however I'm not sure how they solve this with node compat)
- use proper `fetch`, since everything in maintenance or LTS supports it at this point (this would mean dropping support for end of life decade old browsers and runtimes)
