### ISSUE TITLE
Insight fonctionality compatibility

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-js-plugins#410]
Insight is a feature provided by instantSearch to help user track search analytics. 

It is accessible in the [`InstantSearch`](https://www.algolia.com/doc/api-reference/widgets/instantsearch/js/#widget-param-insightsclient) component. Where it asks for an `insightClient`. 

```js
const search = instantsearch({
  // ...
  insightsClient: window.aa
});
```

This feature seems to be working best with algolia [insight library](https://github.com/algolia/search-insights.js) as per the following guide: [`Send Insight Events`](https://www.algolia.com/doc/guides/building-search-ui/going-further/send-insights-events/js/)

But as `InstantSearch` tend to be an open-source project not only accessible to algolia they also provide the possibility of providing your own insight client, see [insight middleware references](https://www.algolia.com/doc/api-reference/widgets/insights/js/). 

My investigation stopped there and I can't say with guarantee another insight API that is not algolia can be used.

**Comment by bidoubiwa** [comment]
With the update on `insight`, it is now only possible to use it with algolia. Closing

**Comment by AntoineDuComptoirDesPharmacies** [comment]
Hi @bidoubiwa,

We are currently evaluating Meilissearch in replacement of Algolia.
Currently with Algolia we are creating an `insigtsClient `from `search-insights` library and we are passing it to : 
* InstantSearch DOM node
* Autocomplete DOM node using `createAlgoliaInsightsPlugin` from `@algolia/autocomplete-plugin-algolia-insights`

The problem is that it produce some errors and insights are not sent.
```
Uncaught Error: Could not infer `queryID`. Ensure `clickAnalytics: true` was added with the Configure widget.
See: https://alg.li/VpPpLt
```

We do not understand your last messasge on this issue. Are the insights and insight client supposed to work ?
Do we have to change the insight client to use one from meilisearch ?

Yours faithfully,
LCDP

**Comment by curquiza** [comment]
Hello @AntoineDuComptoirDesPharmacies 

Maybe @Strift can help here 😊
